#!/bin/bash

# 🚀 RAILWAY BACKEND + VERCEL FRONTEND DEPLOYMENT

clear
echo "🚀 DEPLOY BACKEND TO RAILWAY + FRONTEND TO VERCEL"
echo "================================================"
echo ""
echo "🎯 PERFECT COMBINATION:"
echo "   Backend: Railway (Python/FastAPI) - $0-5/month"
echo "   Frontend: Vercel (React) - FREE"
echo "   Database: MongoDB Atlas - FREE"
echo "   Total: $0-5/month with excellent performance!"
echo ""

# Function to wait for user input
wait_for_user() {
    echo ""
    echo "Press ENTER to continue..."
    read
    clear
}

# Part 1: Railway Backend
echo "🚂 PART 1: DEPLOY BACKEND TO RAILWAY"
echo "===================================="
echo ""
echo "📋 Steps to deploy your Python/FastAPI backend:"
echo ""
echo "1. Go to: https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose: Puneet69/Price-Predictor-Real-Estate-"
echo "6. ⚠️  CRITICAL: Set 'Root Directory' to: backend"
echo "7. Click 'Deploy'"
echo ""
echo "⏱️  Backend will build in 2-3 minutes"
echo ""
echo "🔧 Add MongoDB Environment Variable:"
echo "   - Go to 'Variables' tab"
echo "   - Name: MONGODB_URI"
echo "   - Value: mongodb+srv://price_predictor:vlMUA2FIr48bnJWO@realestate.caqfzde.mongodb.net/property_comparison?retryWrites=true&w=majority&appName=RealEstate"
echo ""
echo "✅ After deployment, copy your backend URL:"
echo "   Should look like: https://backend-production-xxxx.up.railway.app"
echo ""
echo "🧪 Test backend by visiting: [your-backend-url]/docs"
wait_for_user

# Part 2: Vercel Frontend
echo "⚡ PART 2: DEPLOY FRONTEND TO VERCEL"
echo "==================================="
echo ""
echo "📋 Steps to deploy your React frontend:"
echo ""
echo "1. Go to: https://vercel.com"
echo "2. Click 'Sign Up' → 'Continue with GitHub'"
echo "3. Authorize Vercel"
echo "4. Click 'New Project'"
echo "5. Select: Puneet69/Price-Predictor-Real-Estate-"
echo ""
echo "6. ⚠️  CRITICAL PROJECT SETTINGS:"
echo "   Framework Preset: Create React App"
echo "   Root Directory: frontend"
echo "   Build Command: npm run build"
echo "   Output Directory: build"
echo ""
echo "7. ⚠️  ADD ENVIRONMENT VARIABLE:"
echo "   Name: REACT_APP_API_URL"
echo "   Value: [Your Railway backend URL from Part 1]"
echo "   Environment: All (Production, Preview, Development)"
echo ""
echo "8. Click 'Deploy'"
echo ""
echo "⏱️  Frontend will build in 2-3 minutes"
echo ""
echo "✅ After deployment, you'll get a URL like:"
echo "   https://your-app.vercel.app"
wait_for_user

# Testing
echo "🧪 PART 3: TEST YOUR HYBRID DEPLOYMENT"
echo "======================================"
echo ""
echo "🚂 Test Railway Backend:"
echo "1. Visit: [your-backend-url]/docs"
echo "   Should see FastAPI documentation"
echo "2. Test: [your-backend-url]/health"
echo "   Should return status information"
echo ""
echo "⚡ Test Vercel Frontend:"
echo "1. Visit: https://your-app.vercel.app"
echo "   Should load your React app"
echo "2. Test property comparison:"
echo "   Property 1: 123 Main St, San Francisco, CA"
echo "   Property 2: 456 Oak Ave, Los Angeles, CA"
echo "3. Check browser console (F12) for errors"
echo ""
echo "🔗 Integration Test:"
echo "✅ Properties load without errors"
echo "✅ Price predictions display"
echo "✅ Comparison charts appear"
echo "✅ No CORS errors"
echo "✅ Mobile responsive"
wait_for_user

# Troubleshooting
echo "🛠️  TROUBLESHOOTING COMMON ISSUES"
echo "================================="
echo ""
echo "❌ Railway Backend Issues:"
echo ""
echo "🔧 If 'Root Directory' not visible:"
echo "   1. Deploy first (may fail)"
echo "   2. Go to service 'Settings'"
echo "   3. Change 'Source Path' to 'backend'"
echo "   4. Redeploy"
echo ""
echo "🔧 If build fails:"
echo "   1. Check build logs in Railway dashboard"
echo "   2. Verify requirements.txt exists"
echo "   3. Check Python version compatibility"
echo ""
echo "❌ Vercel Frontend Issues:"
echo ""
echo "🔧 If build fails:"
echo "   1. Check build logs in Vercel dashboard"
echo "   2. Verify package.json exists in frontend/"
echo "   3. Check React version compatibility"
echo ""
echo "🔧 If API calls fail:"
echo "   1. Verify REACT_APP_API_URL is set correctly"
echo "   2. Check backend CORS configuration"
echo "   3. Test backend URL directly"
echo ""
echo "❌ Connection Issues:"
echo ""
echo "🔧 Frontend can't reach backend:"
echo "   1. Check REACT_APP_API_URL environment variable"
echo "   2. Ensure backend URL is accessible"
echo "   3. Verify CORS settings in backend/main.py"
wait_for_user

# Success and Next Steps
echo "🎉 SUCCESS! YOUR HYBRID DEPLOYMENT IS COMPLETE"
echo "=============================================="
echo ""
echo "🏆 You now have:"
echo "✅ Railway Backend: Fast Python/FastAPI server"
echo "✅ Vercel Frontend: Lightning-fast React app with global CDN"
echo "✅ MongoDB Atlas: Cloud database"
echo "✅ Auto-deployments: Push to GitHub = automatic updates"
echo ""
echo "💰 Monthly Costs:"
echo "   Railway: $0 (with $5 free credit)"
echo "   Vercel: $0 (free tier)"
echo "   MongoDB: $0 (free M0 tier)"
echo "   Total: $0/month to start!"
echo ""
echo "🌍 Performance Benefits:"
echo "✅ Global CDN for frontend (Vercel)"
echo "✅ Optimized Python backend (Railway)"
echo "✅ Cloud database (MongoDB Atlas)"
echo "✅ Auto-scaling capabilities"
echo "✅ Professional URLs"
echo ""
echo "📱 Your Live URLs:"
echo "   Frontend: https://your-app.vercel.app"
echo "   Backend: https://backend-production-xxxx.up.railway.app"
echo "   API Docs: https://backend-production-xxxx.up.railway.app/docs"
echo ""
echo "🚀 Next Steps:"
echo "□ Bookmark your live URLs"
echo "□ Share with friends and family"
echo "□ Add to your portfolio/resume"
echo "□ Test on different devices"
echo "□ Consider custom domain (optional)"
echo ""
echo "🎯 DEPLOYMENT COMPLETE!"
echo "Your Property Comparison App is now live with the best"
echo "performance and cost combination possible!"
echo ""
echo "=============================================="