#!/bin/bash

# 🚀 RAILWAY MONOREPO DEPLOYMENT FIX

clear
echo "🔧 RAILWAY DEPLOYMENT FIX - MONOREPO ISSUE"
echo "=========================================="
echo ""
echo "❌ PROBLEM IDENTIFIED:"
echo "Railway's Nixpacks failed because it saw both frontend/ and backend/"
echo "directories and couldn't determine what to build."
echo ""
echo "✅ SOLUTION:"
echo "Deploy backend and frontend as separate services with root directories."
echo ""
echo "🚀 FOLLOW THESE EXACT STEPS:"
echo ""

echo "1️⃣  DELETE FAILED SERVICE:"
echo "   👉 In Railway dashboard, click on failed service"
echo "   👉 Go to 'Settings' tab (at bottom)"
echo "   👉 Click 'Delete Service'"
echo "   👉 Confirm deletion"
echo ""

echo "2️⃣  DEPLOY BACKEND SERVICE:"
echo "   👉 Click 'New Service' in Railway"
echo "   👉 Select 'GitHub Repo'"
echo "   👉 Choose: Puneet69/Price-Predictor-Real-Estate-"
echo "   👉 ⚠️  IMPORTANT: Look for 'Root Directory' or 'Source Path'"
echo "   👉 Set Root Directory to: backend"
echo "   👉 Click 'Deploy'"
echo ""

echo "3️⃣  ADD MONGODB ENVIRONMENT VARIABLE:"
echo "   👉 While backend builds, go to 'Variables' tab"
echo "   👉 Add variable:"
echo "       Name: MONGODB_URI"
echo "       Value: mongodb+srv://price_predictor:vlMUA2FIr48bnJWO@realestate.caqfzde.mongodb.net/property_comparison?retryWrites=true&w=majority&appName=RealEstate"
echo ""

echo "4️⃣  DEPLOY FRONTEND SERVICE:"
echo "   👉 In same project, click 'New Service'"
echo "   👉 Select 'GitHub Repo'"
echo "   👉 Choose same repo: Puneet69/Price-Predictor-Real-Estate-"
echo "   👉 ⚠️  IMPORTANT: Set Root Directory to: frontend"
echo "   👉 Click 'Deploy'"
echo ""

echo "5️⃣  CONNECT FRONTEND TO BACKEND:"
echo "   👉 Wait for backend to get a URL"
echo "   👉 Copy backend URL (like: https://backend-production-xxxx.up.railway.app)"
echo "   👉 Go to frontend service → Variables tab"
echo "   👉 Add variable:"
echo "       Name: REACT_APP_API_URL"
echo "       Value: [Your backend URL]"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "✅ Backend builds successfully (2-3 minutes)"
echo "✅ Frontend builds successfully (3-5 minutes)"
echo "✅ Both services show 'Active' status"
echo "✅ You get two working URLs"
echo ""

echo "🧪 TEST YOUR FIXED DEPLOYMENT:"
echo "1. Visit backend URL + /docs (should show FastAPI documentation)"
echo "2. Visit frontend URL (should show your React app)"
echo "3. Test property comparison functionality"
echo ""

echo "💡 WHY THIS FIXES THE ISSUE:"
echo "Railway's Nixpacks now knows exactly what to build:"
echo "- Backend service only sees backend/ directory"
echo "- Frontend service only sees frontend/ directory"
echo "- No more confusion about what to build!"
echo ""

echo "🆘 IF ROOT DIRECTORY OPTION NOT VISIBLE:"
echo "1. Deploy service first"
echo "2. Go to service Settings"
echo "3. Change 'Source Path' to backend or frontend"
echo "4. Redeploy"
echo ""

echo "🚀 ALTERNATIVE QUICK FIX:"
echo "If Railway keeps having issues, try Render.com:"
echo "- Create Web Service (backend) with root: backend"
echo "- Create Static Site (frontend) with root: frontend"
echo "- Same GitHub repo, same environment variables"
echo ""

echo "=========================================="
echo "🎯 SUMMARY: Delete failed service, create two new services"
echo "with proper root directories (backend/ and frontend/)"
echo "=========================================="