#!/bin/bash

# 🚀 INTERACTIVE DEPLOYMENT WALKTHROUGH
# Run this script to get step-by-step deployment guidance

clear
echo "🚀 PROPERTY COMPARISON APP - DEPLOYMENT WALKTHROUGH"
echo "================================================================"
echo ""

# Function to wait for user input
wait_for_user() {
    echo ""
    echo "Press ENTER to continue..."
    read
    clear
}

# Step 1
echo "🏁 STEP 1: CREATE RAILWAY ACCOUNT"
echo "================================="
echo ""
echo "📋 What you need to do:"
echo "1. Open browser and go to: https://railway.app"
echo "2. Click 'Start a New Project' or 'Login'"
echo "3. Choose 'Continue with GitHub'"
echo "4. Authorize Railway to access your GitHub"
echo "5. Complete profile setup"
echo ""
echo "✅ Result: You'll have a Railway account connected to GitHub"
wait_for_user

# Step 2
echo "🔗 STEP 2: CONNECT YOUR REPOSITORY"
echo "=================================="
echo ""
echo "📋 What you need to do:"
echo "1. Click 'New Project' (big purple/blue button)"
echo "2. Select 'Deploy from GitHub repo'"
echo "3. Find and select: Puneet69/Price-Predictor-Real-Estate-"
echo "4. Click 'Deploy Now'"
echo ""
echo "⏱️  Railway will automatically:"
echo "   - Detect Python backend (FastAPI)"
echo "   - Detect React frontend"
echo "   - Read railway.json configuration"
echo "   - Start building both services"
echo ""
echo "✅ Result: Build process starts (takes 5-8 minutes)"
wait_for_user

# Step 3
echo "🔧 STEP 3: CONFIGURE ENVIRONMENT VARIABLES"
echo "=========================================="
echo ""
echo "📋 While your app builds, add MongoDB connection:"
echo ""
echo "1. Go to project dashboard"
echo "2. Click on 'backend' service"  
echo "3. Go to 'Variables' tab"
echo "4. Click 'New Variable'"
echo "5. Add this EXACT variable:"
echo ""
echo "   Variable Name: MONGODB_URI"
echo ""
echo "   Variable Value:"
echo "   mongodb+srv://price_predictor:vlMUA2FIr48bnJWO@realestate.caqfzde.mongodb.net/property_comparison?retryWrites=true&w=majority&appName=RealEstate"
echo ""
echo "6. Click 'Add'"
echo ""
echo "✅ Result: Backend can now connect to your MongoDB Atlas database"
wait_for_user

# Step 4
echo "⏳ STEP 4: WAIT FOR DEPLOYMENT"
echo "=============================="
echo ""
echo "📊 Build progress timeline:"
echo "   ⏱️  0-2 minutes: Installing dependencies"
echo "   ⏱️  2-5 minutes: Building backend (Python/FastAPI)"
echo "   ⏱️  3-8 minutes: Building frontend (React)"
echo "   ⏱️  5-8 minutes: Deployment complete"
echo ""
echo "🔍 What to watch for in logs:"
echo "   ✅ Dependencies installed successfully"
echo "   ✅ Build completed without errors"
echo "   ✅ Deployment successful"
echo "   ✅ Services are running"
echo ""
echo "✅ Result: Both frontend and backend are deployed and running"
wait_for_user

# Step 5
echo "🌐 STEP 5: GET YOUR LIVE URLS"
echo "============================="
echo ""
echo "📋 Copy your deployment URLs:"
echo ""
echo "1. Click on 'backend' service in Railway dashboard"
echo "2. Copy the URL (looks like: https://backend-production-xxxx.up.railway.app)"
echo "3. Click on 'frontend' service"
echo "4. Copy the URL (looks like: https://frontend-production-xxxx.up.railway.app)"
echo ""
echo "📝 Write down your URLs:"
echo "   Backend API: _______________________________"
echo "   Frontend App: ______________________________"
echo ""
echo "✅ Result: You have your live application URLs"
wait_for_user

# Step 6
echo "🔗 STEP 6: CONNECT FRONTEND TO BACKEND"
echo "======================================"
echo ""
echo "📋 Configure frontend to use your backend:"
echo ""
echo "1. In Railway dashboard, click 'frontend' service"
echo "2. Go to 'Variables' tab"
echo "3. Click 'New Variable'"
echo "4. Add:"
echo "   Variable Name: REACT_APP_API_URL"
echo "   Variable Value: [Your backend URL from Step 5]"
echo "5. Click 'Add'"
echo "6. Frontend will automatically redeploy (2-3 minutes)"
echo ""
echo "✅ Result: Frontend can now communicate with backend"
wait_for_user

# Step 7
echo "🧪 STEP 7: TEST YOUR LIVE APPLICATION"
echo "===================================="
echo ""
echo "📋 Testing checklist:"
echo ""
echo "1. Open your frontend URL in browser"
echo "2. Test property comparison with these addresses:"
echo "   Property 1: 123 Main St, San Francisco, CA 94105"
echo "   Property 2: 456 Oak Ave, Los Angeles, CA 90210"
echo "3. Click 'Compare Properties'"
echo ""
echo "✅ Verify these features work:"
echo "   □ Properties load without errors"
echo "   □ Price predictions display"
echo "   □ Comparison charts appear"
echo "   □ No CORS errors in browser console (F12)"
echo "   □ Mobile responsive (test on phone)"
echo ""
echo "🔧 Test backend API:"
echo "   - Visit: [Your backend URL]/docs"
echo "   - Should see FastAPI documentation"
echo "   - Test /health endpoint"
wait_for_user

# Step 8
echo "🎉 STEP 8: SUCCESS! YOUR APP IS LIVE!"
echo "===================================="
echo ""
echo "🏆 Congratulations! Your Property Comparison App is now:"
echo ""
echo "✅ Publicly accessible with HTTPS"
echo "✅ Mobile responsive"  
echo "✅ ML-powered price predictions"
echo "✅ Connected to MongoDB Atlas cloud database"
echo "✅ Secure with environment variables" 
echo "✅ Auto-scaling capable"
echo ""
echo "💰 Monthly costs:"
echo "   Railway: $0 (with $5 free credit)"
echo "   MongoDB Atlas: $0 (free M0 tier)"
echo "   Total: $0/month to start!"
echo ""
echo "🔗 Your live URLs:"
echo "   Frontend: [Your frontend URL]"
echo "   Backend: [Your backend URL]"
echo ""
echo "📱 Share with friends and add to your portfolio!"
wait_for_user

# Step 9
echo "🚀 NEXT STEPS & TROUBLESHOOTING"
echo "==============================="
echo ""
echo "🎯 What to do next:"
echo "□ Bookmark your live URLs"
echo "□ Share app with friends/family"
echo "□ Add to your portfolio/resume"
echo "□ Test on different devices"
echo "□ Monitor usage in Railway dashboard"
echo ""
echo "🛠️  If you encounter issues:"
echo ""
echo "❌ Build fails:"
echo "   → Check build logs in Railway dashboard"
echo "   → Look for missing dependencies"
echo ""
echo "❌ CORS errors:"
echo "   → Verify REACT_APP_API_URL is set correctly"
echo "   → Redeploy frontend service"
echo ""
echo "❌ Database errors:"
echo "   → Check MONGODB_URI environment variable"
echo "   → Test /health endpoint"
echo ""
echo "❌ 404 errors:"
echo "   → Check browser console for JavaScript errors"
echo "   → Verify React routing configuration"
echo ""
echo "📚 Help resources:"
echo "   Railway Docs: https://docs.railway.app"
echo "   Railway Discord: https://discord.gg/railway"
echo "   MongoDB Atlas Support: https://support.mongodb.com"
echo ""
echo "================================================================"
echo "🎉 DEPLOYMENT COMPLETE! YOUR APP IS LIVE! 🎉"
echo "================================================================"