#!/bin/bash

# 🚀 QUICK DEPLOY SCRIPT - Deploy to Railway in 5 minutes!

echo "🚀 PROPERTY COMPARISON APP - RAILWAY DEPLOYMENT"
echo "================================================"
echo "⏰ $(date)"
echo ""

echo "📋 PRE-DEPLOYMENT CHECKLIST:"
echo "✅ MongoDB Atlas configured and tested"
echo "✅ GitHub repository updated with latest code"
echo "✅ Railway.json configuration file ready"
echo "✅ Environment variables prepared"
echo "✅ Frontend and Backend configured"
echo ""

echo "🌐 RAILWAY DEPLOYMENT STEPS:"
echo ""
echo "1️⃣  SIGN UP FOR RAILWAY:"
echo "   👉 Go to: https://railway.app"
echo "   👉 Click 'Login with GitHub'"
echo "   👉 Authorize Railway to access your GitHub"
echo ""

echo "2️⃣  CREATE NEW PROJECT:"
echo "   👉 Click 'New Project' button"
echo "   👉 Select 'Deploy from GitHub repo'"
echo "   👉 Choose: Puneet69/Price-Predictor-Real-Estate-"
echo "   👉 Railway will auto-detect your app configuration"
echo ""

echo "3️⃣  CONFIGURE ENVIRONMENT VARIABLES:"
echo "   👉 In Railway dashboard, go to 'Variables' tab"
echo "   👉 Add this variable:"
echo "   🔑 Variable Name: MONGODB_URI"
echo "   🔗 Variable Value: mongodb+srv://price_predictor:vlMUA2FIr48bnJWO@realestate.caqfzde.mongodb.net/property_comparison?retryWrites=true&w=majority&appName=RealEstate"
echo ""

echo "4️⃣  DEPLOY YOUR APP:"
echo "   👉 Railway will automatically:"
echo "      - Detect Python backend (FastAPI)"
echo "      - Detect React frontend"
echo "      - Install dependencies"
echo "      - Build and deploy both services"
echo "      - Generate HTTPS URLs"
echo ""

echo "⏱️  DEPLOYMENT TIME: 3-5 minutes"
echo ""

echo "🎯 AFTER DEPLOYMENT YOU'LL GET:"
echo "🌐 Backend API: https://your-backend-production.up.railway.app"
echo "🖥️  Frontend App: https://your-frontend-production.up.railway.app"
echo "📱 Mobile-responsive interface"
echo "🔒 Automatic HTTPS encryption"
echo "☁️  Connected to MongoDB Atlas"
echo ""

echo "💰 COST:"
echo "🆓 Free: \$5 credit per month (covers most small apps)"
echo "💳 Paid: \$5/month for unlimited usage"
echo ""

echo "🧪 TEST YOUR DEPLOYED APP:"
echo "1. Open the frontend URL in browser"
echo "2. Try comparing two properties:"
echo "   - Property 1: 123 Main St, San Francisco, CA"
echo "   - Property 2: 456 Oak Ave, Los Angeles, CA"
echo "3. Verify ML price predictions work"
echo "4. Check property comparison charts"
echo ""

echo "🚨 ALTERNATIVE QUICK DEPLOY OPTIONS:"
echo ""
echo "🎨 RENDER (Free Static + \$7/month Backend):"
echo "   👉 https://render.com"
echo "   👉 Connect GitHub repo"
echo "   👉 Deploy static site (frontend) + web service (backend)"
echo ""
echo "🌊 DIGITALOCEAN (\$5-12/month):"
echo "   👉 https://digitalocean.com/apps"
echo "   👉 Uses your .do/app.yaml configuration"
echo "   👉 Enterprise-grade reliability"
echo ""

echo "🎉 DEPLOYMENT COMPLETE CHECKLIST:"
echo "□ Railway account created"
echo "□ GitHub repo connected"
echo "□ Environment variables set"
echo "□ Backend deployed and accessible"
echo "□ Frontend deployed and accessible"
echo "□ MongoDB Atlas connection working"
echo "□ Property comparison functionality tested"
echo "□ Custom domain configured (optional)"
echo ""

echo "🛠️  NEED HELP?"
echo "📚 Railway Docs: https://docs.railway.app"
echo "💬 Railway Discord: https://discord.gg/railway"
echo "📧 Support: hello@railway.app"
echo ""

echo "🚀 READY TO DEPLOY!"
echo "Your Property Comparison App is production-ready!"
echo "Just follow the steps above and you'll be live in minutes!"
echo ""
echo "================================================"